### PR TITLE
User Management Feature: Issue Number 54 [Angular]

### PR DESCRIPTION
**Pull request by AlanFlaherty**
This is an attempt at the user management feature that is required. It is angular, once that is complete I will add the mvc side. There are some requirements missing, 
 * user password edit 
 * settings screen to change the items per page
 * fix mappings in ApplicationModule
 * needs additional testing

It does have add/edit/delete for 
 * Tenants
 * Users
 * Roles

Listings have Edit/Delete/ToggleActive on an action menu, refresh at top right.
 * Added IsActive and Description to Role
 * Angular paged-listing-component-base to implement for paging
 * jquery.validate to show errors before submission if possible (unique ie, username etc require callbacks to be coded)
 * ngx-paginate for paging
 * Implements the AsyncCrudAppService but uses the Management classes for Create/Update/Delete Uses base service for Get and GetAll. 

Feels like there should be an AsyncReadOnlyAppService that implements Get and GetAll in the base. Then more complex situations that use management classes and additional methods could be layered over the top without feeling like your going against the intent of the original classes.

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you. This is a big contribution. I will review it.

**Comment by hikalkan** [comment]
Thanks a lot. I refactored the PR and merged to master. However there are some TODOs (you already know some of them):

* There are missing localizations. I don't mean translation, but hard coded strings like https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/app/roles/roles.component.ts#L47
* We don't use tabs, please use four spaces for .ts files.
* Should complete unit tests.
* Implement MVC + jQuery side too. I made it working but should align with angular version.
* I saw some inline styling. It would be better to move css/less files.
* It would be better to not use jQuery validation because it's not needed - only use angular's validation.
* There are some inconsistency between checkbox usages.
* There are duplicate code. Most of them because of create/update duplication.

We will work on some of them to make it better. If you want to make contribution, you can implement MVC side.

Thank you very much for your work.

**Comment by AlanFlaherty** [comment]
Hi Hikalkan,

I really wasn't expecting it to get merged in this quick. This was an initial working version with a lot of improvements that needed to be made. As you have mentioned the localisation and hardcoded string removal, moving inline styles into css files and unit tests. The method for adding check box values into the dto's needs to be re-written also it does not sit well with databinding, the values should update as the user interacts with the form. The dto mapping using automapper in the ApplicationModule need to be extracted into classes.

I was trying not to put too much functionality in the typescript base classes so the derived classes were a little bloated and needed refactoring. I like the way you implemented the busy screen, it was causing me a lot of annoyance.

I will get unit tests in and have a look back over the menu code. Once that is complete I will get onto the MVC side.

**Comment by hikalkan** [comment]
I merged quickly because I planned to spend time on v2.3 of this template and your PR was the biggest stuff :) As you see I worked a lot and refactored/revised it.

If you have time, let's collaborate on that to finish v2.3 in a short time (1-2 days).
If you have time, you can work on localizations and unit tests and I will work on the rest. Once it's done, we will release this without MVC side aligned. Then we can work on the MVC side in the v2.4.

**Comment by AlanFlaherty** [comment]
Ya thats perfect. I'll get the hardcoded out and localise them and then start on the unit test. It should be a quick win to do unit tests just for the services. I'll create a branch and you can see its as it progresses.

**Comment by AlanFlaherty** [comment]
Hi, changes are in the branch here https://github.com/AlanFlaherty/module-zero-core-template/tree/feature-54-user-management-fixes will merge in the updates to master and get test it beforecreating the pr. I'll start the unit tests once that is complete

**Pull request merged**
