### PR TITLE
Fix issue #379 angular template report error after running NSwag\refresh.bat

### PR DESCRIPTION
**Pull request by personball**
For issue #379 
As I changed the input DTO for User\Role\Tenant paged list api `GetAll`. 
Angular template has auto generate js proxies.
The codes calling js proxies in role.component.ts/user.component.ts/tenant.component.ts get compiling errors.

### CODE REVIEW

**Comment by personball** [comment]
#379 fixed

**Comment by acjh** [comment]
Thanks for the fix! Please use more meaningful commit messages and PR title. 🙂

**Comment by SteveBurgess** [comment]
Looking good, certainly fixes the issue.

I think having a keyword filter that matches to multiple things might lead to confusion in this instance, though. If i'm reading the code right I think as it stands now if I add "admin" as the keyword when requesting Roles it will match "admin" in the description, display name or name, so you lose some of the granularity you had before.

Keeping the properties on the PagedXResultRequestDto's "feels" right. It gives you the flexibility to actually filter on those properties individually. I think it looks nicer on the REST endpoint side as well as it's intuitive as to what you are filtering on when calling GetAll

If you left the properties on those objects you could then extend PagedRequestDto in the Angular components (as you are now) and add in the new properties. Then you can pass them to the proxy getAll call.

Hopefully that makes sense? I'm still finding my feet with ABP and Angular in general so hopefully I’ve not missed something glaring that would stop this from working.

**Comment by personball** [comment]
@SteveBurgess  These are sample code for startup. To use `Keyword` or explicit property `RoleName` or `Name` depends on your requirement.

**Comment by SteveBurgess** [comment]
@personball I don’t disagree at all, requirements will drive exactly how someone would go about implementing something like this for sure.

I’d be interested to hear your thoughts on why you specifically chose this type of implementation? if only to help my understanding of Angular and ABP.

**Comment by tomohleStantec** [comment]
> Looking good, certainly fixes the issue.
> 
> I think having a keyword filter that matches to multiple things might lead to confusion in this instance, though. If i'm reading the code right I think as it stands now if I add "admin" as the keyword when requesting Roles it will match "admin" in the description, display name or name, so you lose some of the granularity you had before.
> 
> Keeping the properties on the PagedXResultRequestDto's "feels" right. It gives you the flexibility to actually filter on those properties individually. I think it looks nicer on the REST endpoint side as well as it's intuitive as to what you are filtering on when calling GetAll
> 
> If you left the properties on those objects you could then extend PagedRequestDto in the Angular components (as you are now) and add in the new properties. Then you can pass them to the proxy getAll call.
> 
> Hopefully that makes sense? I'm still finding my feet with ABP and Angular in general so hopefully I’ve not missed something glaring that would stop this from working.

I agree with Steve - this approach is effectively changing the meaning / functionality of getall() so for those that are upgrading from one version of ABP to another and assuming API's implementation is the same it will break. My 0.02.

**Comment by alirizaadiyahsi** [comment]
Thanks a lot @personball

**Pull request merged**
