### PR TITLE
Enhancement 70 unit tests

### PR DESCRIPTION
**Pull request by AlanFlaherty**
This is an attempt at #70 Add missing unit tests. 
I have created an AsyncServiceTestBase that has the basic crud tests for AsyncServices. If this fits with the aims of the project please let me know if not I can flatten the hierarchy out in each class. 

Small improvements need to be made to the code to cope with the situation when you are dealing with an object hierarchy or aggregate root as in the UserAppService.  Additional generic classes need to be added to line up with the AsyncCrudAppService and the code will need to be refactored to deal with the additional classes (TUpdateDto)

Just need some direction on whether this is correct. I will continue working on this over the next few days.

### CODE REVIEW

**Comment by ismcagdas** [comment]
Hi @AlanFlaherty,

Thanks a lot for your work.
We will review and merge it.

Thanks.

**Comment by AlanFlaherty** [comment]
There are some small changes to the project to be merged in, mostly to allow for checking aggregates in create and updates. And a code tidy up. Should have it checked in tonight or tomorrow.

**Comment by AlanFlaherty** [comment]
As I have stated in the comments testing the dtos like this might be going too far in test code and there is probably a better way to get the same functionality with less test code using attributes. The part that I feel could be improved upon is the createEntity, it should probably have the ability to create multiple entities together rather than just a single entity.

**Comment by ismcagdas** [comment]
We decided not to merge it because we want to keep this template simple.
@AlanFlaherty Thanks for your work anyway.

**Pull request closed without merging**
