### PR TITLE
Add plus sign and apostrophe to email pattern

### PR DESCRIPTION
**Pull request by acjh**
See https://forum.aspnetboilerplate.com/viewtopic.php?p=31427

As used in:

https://github.com/aspnetboilerplate/module-zero-core-template/blob/63f6e3b6147b6df7a08b09a53dad562c57dac17c/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Validation/ValidationHelper.cs#L8

### CODE REVIEW

**Comment by maliming** [comment]
hi @acjh 

I think can use the Isvaild method under EmailAddressAttribute instead of writing a regular expression. 

The web does not need to use regular expressions using the standard w3c email format validation.

**Comment by acjh** [comment]
> I think can use the Isvaild method under EmailAddressAttribute instead of writing a regular expression.

It's not the same: https://github.com/dotnet/corefx/issues/28501
The attribute is for convenience, not for correctness or general use.

> The web does not need to use regular expressions using the standard w3c email format validation.
 
I didn't get that.

**Comment by maliming** [comment]
> The web does not need to use regular expressions using the standard w3c email format validation.

I mean there is standard validation for email in the web.
Such as:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Validation
https://angular.io/api/forms/EmailValidator

**Comment by acjh** [comment]
Both of those allow `user@localhost`, which is generally not expected.

**Comment by maliming** [comment]
I got it, thanks.

**Pull request merged**
