### PR TITLE
Implement MaterialInput directive for BSB theme inputs

### PR DESCRIPTION
**Pull request by vdurante**

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks a lot for your contribution. I will review it and merge.

**Comment by vdurante** [comment]
Thank YOU! I was unable to add the directive to the shared.module.ts file,
so I had to add it to the declarations at app.module and account.module.

One extra detail I am working on is to make it work with other components,
such as ng2-complete, etc.

Still not working 100% of the time. Atm ot works for plain input tags.

**Comment by hikalkan** [comment]
You need to add to declarations and exports if you want to add to shared module. You probably missed to export it.

**Comment by vdurante** [comment]
I will try it tomorrow and push the changes if I succeed

**Comment by vdurante** [comment]
Done! It works.

**Comment by hikalkan** [comment]
Thanks a lot.

**Pull request merged**
