### PR TITLE
Serve angular application from wwwroot

### PR DESCRIPTION
**Pull request by vdurante**
In case the user intends to use the aspnet-core to serve the angular part from wwwroot, after `ng build --prod`, it is possible to do so by mapping paths to wwwroot/index.html using above code.

It may not work when using MVC approach. I haven't tested it.

### CODE REVIEW

**Comment by ismcagdas** [comment]
Hi @vdurante , Thanks for your contribution.
I think this is helpful for people who wants to host angular & host app together.
Our template is designed to be hosted seperately by default.

So, I'm leaving this PR to be an example who wants to use it like you want.
We have a sample document for AspNet Zero here for merging host & client apps https://aspnetzero.com/Documents/Merge-Angular-Client-Server. The project structures are very similar with module zero core template, so it might be helpful as well.

Thanks.

**Comment by vdurante** [comment]
I really need to take some time and read the aspnetzero docs. There is so
much content there as well!

Thank you!

Em 16 de ago de 2017 4:36 AM, "İsmail ÇAĞDAŞ" <notifications@github.com>
escreveu:

**Comment by rqx110** [comment]
the [https://www.aspnetzero.com/Documents/Merge-Angular-Client-Server](https://www.aspnetzero.com/Documents/Merge-Angular-Client-Server) resource is down now.

**Comment by hikalkan** [comment]
We deleted this document since it's already possible to merge while creating a new project.

**Comment by rqx110** [comment]
auto merging is only for asp.net-zero. hopefully adding auto merging option while creating module-zero-core project.

**Comment by hikalkan** [comment]
Hmm.. I think we should implement it for this template too :)

**Pull request closed without merging**
