### PR TITLE
Update iView to 3.x

### PR DESCRIPTION
**Pull request by zorc**
Update iView to 3.x

### CODE REVIEW

**Comment by maliming** [comment]
Have you tested?  🙂

**Comment by zorc** [comment]
No detailed tests have been made, but there are no problems found in the existing functions.

**Comment by zorc** [comment]
PS:In order to successfully import d.ts, I modified tsconfig.json, which may not be the best approach, but I don't know what the consequences are.

**Comment by maliming** [comment]
@zorc Thank you very much, I see a lot of changes.

@xiaochong44 Can you look at it?

**Comment by xiaochong44** [comment]
@maliming Sorry, I didn't reply in time. I was too busy some time ago.There will be more time later.

**Comment by alirizaadiyahsi** [comment]
Thanks a lot @zorc for your effort.

**Pull request merged**
