### PR TITLE
Need some opinion on refactoring and following PR

### PR DESCRIPTION
**Pull request by vdurante**
Hello. I've gathered a list of inconsistencies in the Angular Front-End and Back-End. I am planning a refactoring of some small details and will eventually make a PR to merge all those changes. These are mostly non-breaking changes. I would like some opinions on 2 points:

1. You would like to express your opinion on the points I have raised? If so, let me know.
2. Would you prefer a single PR that includes all changes or segmented PRs?

These are the changes I am planning:

1. remove class login-page in account.component.ts on destroy
2. set angular material theme colors using angular's [default custom theme engine](https://material.angular.io/guide/theming) - remove all unnecessary code from `core.less`
3. text-right on login button
4. change sidebar navigation to include titles and comply with AdminBSB's design and capabilities
5. set angular material's date locale when switching language / initializing application - fix MatDatePicker format and language issues
6. fix users and tenant filter area HTML that triggers x-overflow (scrollbar) to be shown
7. create table class modifier `has-icons` to increase padding and centralize row's data. Remove extra padding from default  `.table tbody tr td, .table tbody tr th` selector - fix unnecessary extra space on tables that don't contain icons
8. don't remove/change AdminBSB input and select functions - just deactivate it
9. modify web's host and core modules to to send exceptions to clients if DEBUG flag is set - facilitate debugging of front-end applications without impacting production.
10. modify dotnet core projects to fix all command line warnings on run/watch
11. modify `abp.swagger.js` to validate if `result.state` equals `1` or `Available` - fixes swagger issues when users define Enum as Strings on swagger generation. Won't impact current behavior.
12. refactor password's change and reset methods - remove front-end complexity, fix localization issues, use usermanager's methods when possible, remove repetitive code between methods
13. modify HTML to prevent caching of HTML and JavaScript - fix issues when the angular application is updated but the browser doesn't update its cache
13. [awating #389] refactor account recovery to comply and reuse password's change and reset methods
14. [validate if desired] refactor seed to facilitate creation of other accounts
15. [validate if possible / desired] get isSelfRegistrationAllowed from back-end. Maybe create a Setting to set a per-tenant IsSelfRegistrationAllowed flag to evaluate if users can self-register or not.
16. [validate if desired] set angular material MatDatePicker to use moment.js as default - makes it easier to work with current nswag generators that uses `moment.js` as default
17. [validate if desired] define standard formatting options of the angular project. Maybe create a .bat file that auto-formats the code before creating PRs - fix HORRENDOUS lack of standards we see in the angular's code today
18. complete localization check looking for inconsistencies and typo issues. This one includes the following strings:
  * `Version` on `account.component.html`
  * `versionText` on `account.component.ts` as `YYYY-MM-DD`
  * add `class="m-l-5 m-r-5"` to anchor on `account-languages.component.html`
  * add ` m-r-5` to icon on `topbar-languageswitch.component.html`
  * add `busy` to card on `login.component.html`
  * `Skins`, `Settings`, and `theme.name` on `right-sidebar.component.html` - add uppercase pipe
  * `Version` on `sidebar-footer.component.html`
  * `versionText` on `sidebar-footer.component.ts` as `YYYY-MM-DD`

### CODE REVIEW

**Comment by vdurante** [comment]
@ismcagdas i didn't know hub would transform the issue into a pull-request. I will reference this issue for each fix

**Comment by vdurante** [comment]
I won't be making more PRs. I will work on the remaining points once there are no pending PRs on the list.

**Comment by ismcagdas** [comment]
Thanks @vdurante it will take some time to review existing PRs.

**Comment by vdurante** [comment]
No hurry. Take your time and let me know of you need anything. Best regards.

**Pull request closed without merging**
