### PR TITLE
issue #4142 Auditing history for owned types not saved

### PR DESCRIPTION
**Pull request by EslamElmadny**
I Added different bounded context with 3 layers (entityframework , application, domain) and added vehicle entity in domain layer with it's appservice to add and update ... 
Then i added VehicleAppServiceTests to check if i update any owned type it will save entity history for this entity or not ...

### CODE REVIEW

**Comment by maliming** [comment]
I guess you opened the wrong PR.

**Comment by EslamElmadny** [comment]
@maliming  sorry, but how ?

**Comment by ismcagdas** [comment]
@EslamElmadny this PR contains specific code to your project. Probably you just wanted to include a small part of it to the PR but it seems like you have included many unrelated changes.

**Comment by EslamElmadny** [comment]
Creating different bounded context is required to generate the issue I'm facing .. all these changes are related to same topic

**Pull request closed without merging**
