### PR TITLE
Add auditlogs page

### PR DESCRIPTION
**Pull request by jozzlee**
Just add a simple auditlogs page.

### CODE REVIEW

**Comment by jozzlee** [comment]
I'm sorry to confuse the changes of PR #511, I don't know how to remove them.

**Comment by ismcagdas** [comment]
@jozzlee thanks I will check it.

**Comment by demirmusa** [comment]
> I'm sorry to confuse the changes of PR #511, I don't know how to remove them.

You can keep commiting to that branch it will be inclueded to your pull request.

**Comment by ismcagdas** [comment]
@jozzlee thank you for your effort but unfortunately we will not be able to accept this PR. AspNet Boilerplate Framework's startup templates are meant to be simple and they are designed to quickly start new projects. We don't want to include such business related features to free templates since we already provide this functionality in AspNet Zero.

Thanks again and sorry for not accepting the PR.

**Pull request closed without merging**
