### PR TITLE
React package updates

### PR DESCRIPTION
**Pull request by AllyMurray**
[Related issue](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4575)

React Scripts TS, React App Rewired and React App Rewire Less now all
removed because they are deprecated or not well maintained.

Create React App Configuration Override and Craco Ant Design added in
place of the above packages.

All other packages updated.

Various issues resolved due to package changes:
 - Import statements updated for CRA

 - Config re-written for Craco

 - All linting warning fixed

 - Antd forms are now generic and the type must be specified when
calling Form.create

 - All Antd Menu items have had the anchor links removed, anchor links
with no href are bad for accessibility and the menu item itself allows
specifying an onClick event.

 - Antd now has link type buttons so anywhere an anchor link was used
has been changed to use a button. The only place this is not true is the
Forgot Password link because this does not seem to be implemented.

 - Any anchor links with target="_blank" now have
rel="noopener noreferrer" too.

### CODE REVIEW

**Comment by ismcagdas** [comment]
@AllyMurray thanks a lot for your great contribution 😄 . Currently tests are failing but it seems like it is related to https://github.com/sharegate/craco/issues/89.

**Comment by AllyMurray** [comment]
You're welcome, the project was a great help to me, was only fair I contribute back. I should have mentioned that I was aware that the tests were failing, this was also the case before changing any packages. Granted it failed for a different reason before.

I didn't bother doing anything about it because I planned to open a new issue for improving the tests. Currently, there is only the one test which is the test that's created with CRA. It would be good to fix it and improve the test coverage.

**Comment by ismcagdas** [comment]
@AllyMurray you are right, tests were failing before and we are hoping to increase the test count in the future. Thanks a lot again for your contribution.

**Comment by fmartin40** [comment]
Great work :) Thanks a lot @AllyMurray

**Pull request merged**
