### PR TITLE
Resolve #285 - Removed permissions remain checked in Angular UI

### LINKED ISSUE #285: Removed permissions remain checked in Angular UI
Moved from https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3598

### PR DESCRIPTION
**Pull request by alirizaadiyahsi**

### CODE REVIEW

**Comment by acjh** [comment]
This PR is sufficient to fix the bug for that use case.
But here are more-complete solutions that include the prohibited permissions, for consideration:
1. Return all related permissions (as before this PR) and a separate list for granted permissions.
2. Return two separate lists for permissions (granted) and prohibited permissions.
3. Return `PermissionSettingDto` with `IsGranted` property.

**Comment by alirizaadiyahsi** [comment]
Yes @acjh I know, but we thought something like your suggestion that is already implemented in paid product. But we wanted to use CRUD app service method. 

@ismcagdas what do you think?

**Comment by ismcagdas** [comment]
@acjh I think this solution https://github.com/aspnetboilerplate/module-zero-core-template/pull/286#issuecomment-403494331 requires more work :).

Are there any scenarios which this PR doesn't cover ?

**Comment by acjh** [comment]
If there is a way to prohibit a role permission, there should be a way to know it is prohibited.

Actually, shouldn't deselecting a role permission remove the grant entry rather than prohibit it?
If so, we can include that fix in this PR instead.

**Comment by ismcagdas** [comment]
> Actually, shouldn't deselecting a role permission remove the grant entry rather than prohibit it?

Yes, this is true :). 
@alirizaadiyahsi we should implement it as @acjh suggested then.

**Pull request merged**
