### PR TITLE
Add swagger authentication helpers

### LINKED ISSUE #61: Current user did not login to the application! on Host project
When I execute api on swagger of host project. Could you help me explain how to do on it. 

Thanks

image

### PR DESCRIPTION
**Pull request by acjh**
Fixes #61 

The `abp.js` included is a lite version.
The `on-complete.js` adds 3 helper methods in the `abp.swagger` namespace:
- `addAuthToken()` adds the `authToken`, which can be set via `abp.auth.setToken(authToken, expireDate)`.
- `addCsrfToken()` adds the `csrfToken`, if the user is logged in to the application.
- `login()` prompts for `tenantId`, `usernameOrEmailAddress` and `password`, logs in via token-based authentication at `/api/TokenAuth/Authenticate` and then calls `addAuthToken()` automatically.

### CODE REVIEW

**Comment by acjh** [comment]
I added `abp.auth.tokenHeaderName = 'Authorization';` to the `abp.js`, which is used in `on-complete.js`.

**Comment by acjh** [comment]
Example flow 1: User is logged into application
- Run `abp.swagger.addCsrfToken()` in the console to authenticate
- Refresh to unauthenticate

Example flow 2: User is logged in via Postman
- Run `abp.auth.setToken(authToken)` and `abp.swagger.addAuthToken()` in the console to authenticate
- Refresh to unauthenticate
- Subsequently, run `abp.swagger.addAuthToken()` in the console to authenticate

Example flow 3: User is not logged in
- Run `abp.swagger.login()` in the console to authenticate
- Refresh to unauthenticate
- Subsequently, run `abp.swagger.addAuthToken()` in the console to authenticate

**Comment by sebitsi** [comment]
Hi @acjh.

I tried your code. Works perfect. Sometimes !
I think it is not problem in your code.

If i refresh browser (chrome, edge) and try to execute **abp.swagger.addCsrfToken()** in console sometimes i got error "Cannot read property 'addCsrfToken' of undefined.
after one or more (random) refreshes method exists again and can be executed.

After some research i noticed that problem is in code:

_.each(JSConfig.onCompleteScripts ..... which loads aditional files in swagger-UI.

Looks like second script is loaded before initialization of first is ended.

If i put scripts into one file everythink works perfect,

I think author sholu use $.getScript with callback parameter and continue loading after previous load is finished.

**Comment by acjh** [comment]
Thanks for your feedback!

I think there are 3 ways:
1. Put scripts into one file.
Pro: Simple and clean.
Con(sideration): Should `abp.swagger` helper methods be in `abp.js`?

2. Call `$.getScript('/swagger/ui/abp.js')` at the start of `on-complete.js` instead of injecting.
Pro: Dependency is clear.
Con: Ugly, need to define `abp.swagger` methods in callback.

4. Do `var abp = abp || {};` at the start of `on-complete.js`.
Pro: Simple and clean.
Con: Dependency on `abp.js` is not obvious.

**Comment by sebitsi** [comment]
Hi, 

1. abp.swagger helper should not be in abs.js. 
2. Yes is ugly but works and all logic is in our code in helpers file 
3. It is simple and cleand but and i try. It's working.

I wote for 3rd options.

But there is 4th. swagger-UI should be repaired. ;)

**Comment by sebitsi** [comment]
Now we have helpers. Fine.

Did you find the way how bind "Authorize" button and helper method ?
It will be nice if we could just click on button and "teach" UI what shuld put into request header,

**Comment by acjh** [comment]
You mean create a button on `/swagger/ui`? You can [hack](https://en.wikipedia.org/wiki/Hacker_culture) the DOM with JS, but shouldn't be in this PR.

**Comment by sebitsi** [comment]
No, of course not. Not in this PR and no hack.

Swagger UI follows OpenAPI specification/swagger generated json file.
If there is security definitions then authorize button is included and some security schemas implemented.

So we should handle swagger ui with security definitions not hacks.

I just ask if you found some useful informations how to create custom authorisation schema like:
"take this and put into request."

We now have helpers to implement "take this and put into request." All we need to find out how
to define this custom schema.

Yes and this is for another PR.

**Comment by acjh** [comment]
Okay, I've not looked into that.

**Comment by sebitsi** [comment]
Hi again.

I try to replace your abp.js lite file with original abp.js.
After file replace ,code is broken because in original abp.auth.tokenHeaderName is missing.

Just for info.

**Comment by acjh** [comment]
Yes, already noted in [my comment](https://github.com/aspnetboilerplate/module-zero-core-template/pull/87#issuecomment-316745745).

**Comment by acjh** [comment]
> Did you find the way how bind "Authorize" button and helper method ?
It will be nice if we could just click on button and "teach" UI what shuld put into request header,

@sebitsi See #108

**Comment by sebitsi** [comment]
Hi @acjh.

I have same code as yours in #108.
It works perfect if we paste token into input filed.

I'm still searching the way how bing button click event to your helpers.
Without hack of course.

**Comment by acjh** [comment]
> I'm still searching the way how b[r]ing button click event to your helpers.
Without hack of course.

This doesn't seem to be supported.

Which helper do you need? #108 already supports [**Example flow 2**](https://github.com/aspnetboilerplate/module-zero-core-template/pull/87#issuecomment-316750655).
Swagger supports **Example flow 3** for OAuth2, which requires IdentityServer, so set this up separately.
**Example flow 1** (using anti-CSRF token) is unconventional for API, but can be done like Example flow 2.

**Comment by ismcagdas** [comment]
@acjh, thank you very much for your effort.

**Comment by jaszb** [comment]
i`'m evaluating ABP for a university site and trying to demo the web Api via swagger ui.  
i'm intending to  use .net core web api + angular.

so , following the steps above for scenario 3 (User is not logged in)

step 1: Run abp.swagger.login() in the console to authenticate
step 2: Run abp.swagger.addAuthToken()

I then try "http://localhost:21021/swagger/#!/Role/ApiServicesAppRoleGetAllPermissionsGet"

all i get is 401 - what am i missing?

**Comment by acjh** [comment]
Try this fix: https://github.com/aspnetboilerplate/module-zero-core-template/pull/134/files

```diff
- swaggerUi.api.clientAuthorizations.add(abp.auth.tokenHeaderName, cookieAuth);
+ swaggerUi.api.clientAuthorizations.add('bearerAuth', cookieAuth);
```

**Comment by jaszb** [comment]
Thank you!! - made my day :-)

**Comment by jaszb** [comment]
strange - the fix says it was merged 18 days ago...but i guess not made it into the release yet?

**Comment by acjh** [comment]
Released in **v3.4.0** on Nov 21.

**Comment by mohammad-shadmehr** [comment]
Hey Aaron,
I have just downloaded a new project for ABP Zero but that did not include these changes despite you have mentioned that it has already been released

**Comment by acjh** [comment]
@mohammad-shadmehr Do you mean [ASP.NET Zero](https://github.com/aspnetzero)?

**Comment by mohammad-shadmehr** [comment]
Yes I mean the ASP.NET Zero.

**Comment by ismcagdas** [comment]
@mohammad-shadmehr it is not included in AspNet Zero yet but I created an issue https://github.com/aspnetzero/aspnet-zero-core/issues/723.

**Pull request merged**
