### PR TITLE
Fix vue template when add more routers in appRouters

### PR DESCRIPTION
**Pull request by personball**
In vue template:
While add more router item in appRouters, in store/app.ts updateMenulist will report error. 

router/router.ts

vue_error

### CODE REVIEW

**Comment by ismcagdas** [comment]
Thanks a lot @personball

**Comment by acjh** [comment]
How about creating a suitable interface like #349?

**Comment by personball** [comment]
@acjh  Thanks for your suggestion. I will try.

@ismcagdas  Please wait.

**Comment by personball** [comment]
@acjh Please review.

@ismcagdas  This pr is completed.

**Pull request merged**
