### PR TITLE
rewrite template use typescript

### PR DESCRIPTION
**Pull request by xiaochong44**
rewrite template use typescript
update vue cli to 3.0
alter abp.js remove jquery

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you @xiaochong44 for the great contribution. We will test it and merge soon.

**Comment by alirizaadiyahsi** [comment]
Hi @xiaochong44 , thank for your effort. This is great work.

I have some advices:

- Users and roles menu/pages are missing. (I can see code of these pages, but I can't see in UI)

image


- There is no need menu that named "Manage Menu". All menus can be the same level. No need extra level. Like above image.

- Bug: If I locked the screen, than enter wrong password, I can unlocked the screen again. (I know this is an extra feature, but as you know users want to run feature without any issue :) )

- Language selection is missing. 

- Why I can't add new tenant? Button is disabled.

image

- And edit is disabled, too.

image

Feel free to give feedback/suggestion/explanation...

**Comment by xiaochong44** [comment]
@alirizaadiyahsi  Sorry,i write this template in my project,i have modify permission name.
Now,i change template permission name,and unlock add password validate.
but menus level no change,It is a  big changes.

**Comment by alirizaadiyahsi** [comment]
@xiaochong44 great! One more question, there is no "language-select" implementation for admin panel, right? I mean like this:

image

--------

> "but menus level no change,It is a big changes."

It is ok.

**Comment by xiaochong44** [comment]
@alirizaadiyahsi  
Ok,i changed it,please review

**Comment by ismcagdas** [comment]
@xiaochong44 thanks a lot again for your awesome contribution 😄 .
I have a few notes. Just tell us if you have time to do this or not. If you don't have time, we can handle it ourselfs.

1. Can we split ts and html content into different files like it is done in here https://github.com/alirizaadiyahsi/Sphinx/tree/master/src/Sphinx.Web.Spa.Vue/ClientApp/components/app/counter ?

2. I know that this is part of your project but in ABP templates, we want to include English content & comments instead of chinese. If you want to keep those in chinese in your project, we can accept the PR and change the content by ourselfs.

**Comment by xiaochong44** [comment]
@ismcagdas
1. Vue official recommendation single file components,so i like this. if you like different files,can you  split it by yourself
2,. sorry,my English is very bad.please translate it yourself

**Comment by ismcagdas** [comment]
@xiaochong44 thanks a lot for your answers and thank you for your great contribution agian. We will handle the translation. We will also think about seperating the files, we are not sure yet.

**Comment by ismcagdas** [comment]
@xiaochong44 there are many conflicts with your branch and master branch. Can I take your branch and override existing vue folder's content ? I'm asking because your commits will not be visible in that case.

**Comment by xiaochong44** [comment]
@ismcagdas ok, no problem,I deleted all the files and rewritten the template

**Comment by dongfo** [comment]
awsome!
but i find that vue-cli 3.0 is a beta version . And It seems TypeScript has less users than es.

**Comment by ismcagdas** [comment]
@dongfo vue-cli will be the official tool for VueJs project I guess, so this is a right choice even if it is in beta.

> And It seems TypeScript has less users than es.

You are right about this but since we are using Typescript in Angular template, we didn't think that this might be a problem.

**Comment by xiaochong44** [comment]
@dongfo  If you don't like TypeScript, you can create vue component use es,one part is TypeScript component, the other use es is ok. or you rewrite the template

**Comment by hikalkan** [comment]
Hi @WinChance 

it's hard for us to manage too many templates. You can start with MVC&JQuery version which does not include Typescript.

**Pull request merged**
